#ifndef WHEELCHAIR_FIRMWARE_VERSION_H
#define WHEELCHAIR_FIRMWARE_VERSION_H

#define FIRMWARE_NAME "Wheelchair ESP32-S3 Firmware"
#define FIRMWARE_VERSION "0.7.0"
#define HARDWARE_TARGET "ESP32-S3"

#endif
